export {default as Home} from './Home'
export {default as NotFound} from './NotFound'
export {default as Result} from './Result'
export {default as Schedule} from './Schedule'
export {default as ScoreBoard} from './ScoreBoard'
export {default as Stage} from './Stage'
export {default as TVscreen} from './TVscreen'